### ISSUE TITLE
Can not build rust-secp256k1 inside CosmWasm contracts

### ISSUE THREAD

**Issue by raress96** [CosmWasm/optimizer#162]
Hello, as described here https://github.com/rust-bitcoin/rust-secp256k1/issues/748#issuecomment-2405121373, it seems that the `rust-secp256k1` library can not be built using `rust-optimizer` when in WASM context.

The library should support running in WASM context, but I am not quite sure where the error could reside...

**Comment by chipshort** [comment]
Hi, the rust-secp256k1 library uses a C library under the hood, which seems not well supported for the wasm target. Does the crate claim to work for the wasm target?
Does it work if you just build using `cargo build --target wasm32-unknown-unknown`?

**Comment by chipshort** [comment]
Also: Do you have this problem because it's somewhere in your dependency or do you want to use the crate directly?
Because if you just need secp256k1, then you can use the corresponding APIs we provide: https://docs.rs/cosmwasm-std/2.1.4/cosmwasm_std/trait.Api.html#tymethod.secp256k1_verify

**Comment by raress96** [comment]
Unfortunately it is somewhere in the dependency tree... The library should support other wasm targets, I will have to check exactly what the problem is here.

**Comment by chipshort** [comment]
While looking at their repo, it looks like they [only support wasm32-wasi](https://github.com/rust-bitcoin/rust-secp256k1/issues/485), not wasm32-unknown-unknown (which is what CosmWasm contracts use), so I'll close here, since it's not an optimizer issue.
