### ISSUE TITLE
Specifying build options

### ISSUE THREAD

**Issue by JoowonYun** [CosmWasm/optimizer#80]
Often contracts have separate `features` developed.

What does  think about that option takes it as a parameter?

https://github.com/CosmWasm/rust-optimizer/blob/317e459b391f2ddd23422477edfd622e1362f10a/build_workspace/src/main.rs#L66-L71

**Comment by webmaster128** [comment]
That makes reproducible builds significantly harder since you need to store options as well somewhere. Can't you use default features? What kind of feature flags do you need?

**Comment by JoowonYun** [comment]
Actually, I am developing a contract, and I want to use the contract in common on different chains. 

For example, Terra has a different concept called tax, and I am thinking about using only that part as `features=terra`.

**Comment by webmaster128** [comment]
Okay, makes sense. However, don't you need different cosmwasm-std versions for Terra and other chains anyways? Also isn't Terra tax 0 these days?

**Comment by JoowonYun** [comment]
Yes, it's a different version, but Terra keep following up on the latest version, and I think all projects will be the same. Eventually, I think there will be a release for each version. This is because I do not want to separate and manage the same logic.

Terra tax is also currently 0, but since it is a parameter, it can be changed at any time, so there is a risk to remove it. 😅

**Comment by dakom** [comment]
I ran into a similar issue where I wanted to deploy a slightly tweaked version of a contract, but don't want to worry about a fork or branch going stale as other updates are made.

Features are bread-and-butter in Rust dev and a must-have for this tool imho. In the meantime I just run cargo and wasm-opt manually.

**Comment by JoowonYun** [comment]
But I found a new problem with what I want.

When wasm is uploaded, it checks for `supportedFeatures `, which can't distinguish any another features I want. 

But it happens in default which I didn't include as a feature. I need to check the code of this part a bit more to see if I did the build wrong.
https://github.com/CosmWasm/wasmvm/blob/cb1747a1393c4e0776185ad2c5c1dca9c1802de2/api/lib.go#L101-L114

**Comment by webmaster128** [comment]
> When wasm is uploaded, it checks for `supportedFeatures`, which can't distinguish any another features I want.

Which error do you get? The CosmWasm feature system is independent to the Rust feature system. It's a way to ensure the chain provides everything that the contract needs.

**Comment by JoowonYun** [comment]
> > When wasm is uploaded, it checks for `supportedFeatures`, which can't distinguish any another features I want.
> 
> Which error do you get? The CosmWasm feature system is independent to the Rust feature system. It's a way to ensure the chain provides everything that the contract needs.

As mentioned above, I am developing with `default` and `features=terra`. I'm currently building with rust-optimizer in this repo and I'm pretty sure it will build without terra features. But when I do `wasmd tx wasm store test.wasm`, I get the following error.
```Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract requires unsupported features: {"terra"}: create wasm contract failed: invalid request```

I'm not sure if the feature was included in wasm because I defined the feature incorrectly, or if the analyze_code is wrong.

**Comment by JoowonYun** [comment]
@webmaster128 
I have my work in this commit. https://github.com/terraswap/terraswap/pull/44/commits/aea4e66d869878fc8608a37bf7fde6f17ccb7950

It is divided into default and terra. If cosmwasm/rust-optimizer is used, it is default, and if terraswap/rust-optimizer is used, it is an optimizer with features=terra added.

**Comment by JoowonYun** [comment]
> > > When wasm is uploaded, it checks for `supportedFeatures`, which can't distinguish any another features I want.
> > 
> > 
> > Which error do you get? The CosmWasm feature system is independent to the Rust feature system. It's a way to ensure the chain provides everything that the contract needs.
> 
> As mentioned above, I am developing with `default` and `features=terra`. I'm currently building with rust-optimizer in this repo and I'm pretty sure it will build without terra features. But when I do `wasmd tx wasm store test.wasm`, I get the following error. `Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract requires unsupported features: {"terra"}: create wasm contract failed: invalid request`
> 
> I'm not sure if the feature was included in wasm because I defined the feature incorrectly, or if the analyze_code is wrong.

I solved this problem. `cfg(not(feature=` caused the problem.

**Comment by JoowonYun** [comment]
> ~But I found a new problem with what I want.~
> 
> ~When wasm is uploaded, it checks for `supportedFeatures`, which can't distinguish any another features I want.~
> 
> ~But it happens in default which I didn't include as a feature. I need to check the code of this part a bit more to see if I did the build wrong.~ ~https://github.com/CosmWasm/wasmvm/blob/cb1747a1393c4e0776185ad2c5c1dca9c1802de2/api/lib.go#L101-L114~

The problem with this comes from the code below.
https://github.com/terra-money/terra-cosmwasm/blob/094dc24caa9d417e528e32cc2e44fa19c576599b/packages/terra-cosmwasm/src/lib.rs#L14-L17

No problem with supportedFeatures.

**Comment by CyberHoward** [comment]
@JoowonYun cargo now allows for weak dependencies that are only compiled when a feature is requested. [It was recently stabilized](https://rust-lang.github.io/rfcs/3143-cargo-weak-namespaced-features.html). 

I'd also like to compile/optimize my contracts based on feature flags that enable these optional dependencies as our infrastructure aims to be chain-agnostic.

**Comment by webmaster128** [comment]
> The problem with this comes from the code below. https://github.com/terra-money/terra-cosmwasm/blob/094dc24caa9d417e528e32cc2e44fa19c576599b/packages/terra-cosmwasm/src/lib.rs#L14-L17
> 
> No problem with `supportedFeatures`.

Yeah, this will require the feature "terra". If a chain does not have it, you cannot use terra-cosmwasm as a dependency of you contract.

**Comment by whalelephant** [comment]
Hi, I am also looking for this because we have similar contracts with minor differences for different chains and will communicate with each other via IBC. They are tested and compiled with the features flag for different features. 

@CyberHoward / @webmaster128 any updates on your ends?

**Comment by kerber0x** [comment]
I am also looking for the same feature, is this something that you guys are considering implementing? @webmaster128

**Comment by webmaster128** [comment]
To me this is basically blocked by reproducible builds. When you don't need reproducible builds, you can just compile your `*.wasm`s [like this](https://github.com/confio/cw-ibc-demo/blob/ce3112721e3b1d7650d848823e3055b2c2328d13/devtools/build_integration_wasm.sh#L13-L17).

If you look at the discussions around gov proposals on Osmosis, people already have a very hard time providing the relevant information to allow contract verification. At the moment you need 1. source code, 2. builder image incl. version. I don't want to create the need for a 3rd parameter here which would be builder options.

I don't see a solution that adds this flexibility without increasing the communication burden and the burden on verifiers. This is why I think those things should like in the source code with one (wrapper) contract for each target chain.

**Comment by ethanfrey** [comment]
I fully understand the request, and we should provide some easy solution here.
I also fully support Simon's concerns about reproducibility.
We will have to find some solution here or I smell some forks.

My first thought is this.

1. Create your basic package `my-protocol-base` with all the various feature flags
2. For each chain/feature, create a new minimal package `my-proto-osmo`, `my-proto-terra`. This package would need two thing:
  a. Cargo.toml importing `my-protocol-base` with the feature enabled
  b. a super minimal `lib.rs` that just re-exports the msg/entry points (if needed for force import and compiling wasm)

Then `rust-optimiser` will run proper on `my-proto-osmo`, `my-proto-terra` and they would have no code dup (just a git repo saying "compile with this feature flag").

I have no tried it, but would be happy for someone with such a project to try it out and report. If it works, we could at least document this possibility. This does not preclude adding support for feature flags in the optimiser, but would be a valid solution short-term, while we discuss if this is the best long-term solution, or use other.

It does not involve changing core tools, but can be opted in per project, which is easy for adoption

**Comment by webmaster128** [comment]
#129 shows a promising approach to solve this problem by letting the optimizer build multiple versions of the contract **without taking additional build arguments**. It keeps the problem as simple as source code + builder image for the folks reproducing.

**Comment by dakom** [comment]
fwiw the way we're tackling this is perhaps a bit funny, but it works:

SETUP

1. Contract has `default = []` in it's `[features]`
2. All building goes through a thin shell script with env vars for arm64 or not, features or not, etc. to control things

TYPICAL RUN

1. just runs the optimizer as you'd expect (or via arm64 version)

FEATURES RUN

1. Replaces `default = []` with the features (e.g. `default = ["foo"]`) via a `sed` one-liner
2. Builds
3. Sets the default back to blank

Yeah it's a bit goofy, but it works and doesn't need any special support from the optimizer

**Comment by apollo-sturdy** [comment]
@dakom Would you be able to share the one liner? Need a quick fix to run on our CI.

**Comment by webmaster128** [comment]
Solution from https://github.com/CosmWasm/optimizer/pull/148 will be shipped as part of 0.16.0

**Comment by webmaster128** [comment]
You can test 0.16.0 now – should work
